/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajoencargado4;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author 20162
 */
public class ejercicio6 extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio6
     */
    static ArrayList<String> MES;
    ArrayList<Double> ListaDulces;
    ArrayList<Double> ListaBebidas;
    ArrayList<Double> ListaConservas;
    int cont=0;
    public ejercicio6() {
        initComponents();
        MES = new ArrayList<>();
        ListaDulces = new ArrayList<>();
        ListaBebidas = new ArrayList<>();
        ListaConservas = new ArrayList<>();
        this.setLocationRelativeTo(null);
        this.setTitle("ejercicio 6");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmes = new javax.swing.JTextField();
        txtcantidadconcervas = new javax.swing.JTextField();
        txtcantidaddulces = new javax.swing.JTextField();
        txtcantidadbebidas = new javax.swing.JTextField();
        btngrabar = new javax.swing.JButton();
        btncalcular = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtmesproductomayor = new javax.swing.JTextField();
        txtpromedioanual = new javax.swing.JTextField();
        txtmesmenorregistro = new javax.swing.JTextField();
        txtdepartamentomenorproduccion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("MES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 21, -1, -1));

        jLabel2.setText("DULCES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel3.setText("BEBIDAS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel4.setText("CONCERVAS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        getContentPane().add(txtmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 190, -1));
        getContentPane().add(txtcantidadconcervas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 140, -1));
        getContentPane().add(txtcantidaddulces, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 140, -1));
        getContentPane().add(txtcantidadbebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 140, -1));

        btngrabar.setText("GRABAR");
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btngrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        btncalcular.setText("CALCULAR");
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btncalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jLabel5.setText("MES DE MI MAYOR PRODUCCION DE DULCES");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel6.setText("PROMEDIO ANUAL DE LOS COSTOS DE PRODUCCION  BEBIDAS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel7.setText("EN QUE MES SE REGISTRO EL MENOR COSTO DE PRODUCTO DE BEBIDAS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel8.setText("CUAL FUE EL DEPARTAMENTO DE MENOR PRODUCCION EN AGOSTO");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));
        getContentPane().add(txtmesproductomayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 250, -1));
        getContentPane().add(txtpromedioanual, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 230, -1));
        getContentPane().add(txtmesmenorregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 210, -1));
        getContentPane().add(txtdepartamentomenorproduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 220, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        // TODO add your handling code here:
       addListasControl();
        limpiar();
    }//GEN-LAST:event_btngrabarActionPerformed

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
        // TODO add your handling code here:
        MayProducDulces();
        PromedioAnualBebidas();
        menorCostoBebidas();
        menorProduccionAgosto();
    }//GEN-LAST:event_btncalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ejercicio6  ej =  new ejercicio6();
                ej.setVisible(true);
                ej.addMeses();
                ej.txtmes.setEditable(false);
                //new ejercicio6().setVisible(true);
            }
        });
    }
    
    public void addMeses(){
        MES.add("Enero"); 
        MES.add("Febrero");
        MES.add("Marzo");
        MES.add("Abril");
        MES.add("Mayo"); 
        MES.add("Junio");
        MES.add("Julio"); 
        MES.add("Agosto");
        MES.add("Septiembre");
        MES.add("Octubre");
        MES.add("Noviembre");
        MES.add("Diciembre");
    }
    
    public void addListas(){        
        if(ListaDulces.size()<=12){
            if(ListaBebidas.size()<=12){
                if(ListaConservas.size()<=12){                    
                    ListaDulces.add(Double.parseDouble(this.txtcantidaddulces.getText()));
                    ListaBebidas.add(Double.parseDouble(this.txtcantidadbebidas.getText()));
                    ListaConservas.add(Double.parseDouble(this.txtcantidadconcervas.getText()));                    
                }else{
                    throw new RuntimeException("Supera el limite");
                }
            }else{
                throw new RuntimeException("Supera el limite");
            }
        }else{
            throw new RuntimeException("Supera el limite");
        }
    }
    
    public boolean primerIf(){
            if(txtcantidaddulces.getText()!=null){
                if(txtcantidadbebidas.getText()!=null){
                    if(txtcantidadconcervas.getText()!=null){
                        return true;
                    }else
                        return false;
                }else
                    return false;
            }else
                return false;
    }
    
    public boolean segundoIf(){
        if(!txtcantidaddulces.getText().equals(""))
            if(!txtcantidadbebidas.getText().equals(""))
                if(!txtcantidadconcervas.getText().equals(""))
                    return true;
                else
                    return false;
            else
                return false;
        else
            return false;
    }
    
    public boolean tercerIf(){
        if(!Character.isDigit(Integer.parseInt(txtcantidaddulces.getText())))
            if(!Character.isDigit(Integer.parseInt(txtcantidadbebidas.getText())))
                if(!Character.isDigit(Integer.parseInt(txtcantidadconcervas.getText())))
                    return true;
                else
                    return false;
            else
                return false;
        else
            return false;
    }
    
    public void addListasControl(){
        try{
            if(primerIf()){
                if(segundoIf()){
                    if(tercerIf()){
                        if(muestraMes()){
                            addListas();
                        }else
                            JOptionPane.showMessageDialog(null," Mes aun no generado");                        
                    }else
                        JOptionPane.showMessageDialog(null,"ingrese solo numeros");
                }else
                    JOptionPane.showMessageDialog(null," Campos vacios");
            }else
                JOptionPane.showMessageDialog(null," ingrese solo numeros");            
                                                
        } catch (Exception e) {
                JOptionPane.showMessageDialog(null," Campo nulo");
        }finally{
            
        }
        
    }
    
    public boolean muestraMes (){
        for(String s: MES)
            if(this.txtmes.getText().equalsIgnoreCase(s))
                return true;            
        return false;        
    }
    
    public void limpiar(){        
        this.txtcantidaddulces.setText("");
        this.txtcantidadbebidas.setText("");
        this.txtcantidadconcervas.setText("");
        if(cont==11)
            cont=0;        
        this.txtmes.setText(MES.get(cont));
        cont++;
    }
    
    
    public void MayProducDulces(){
        int indice=0;
        double max = ListaDulces.get(0);
        for(int i=0;i<ListaDulces.size();i++)
            if(ListaDulces.get(i)>=max)
                indice = i;                
        this.txtmesproductomayor.setText(""+MES.get(indice));
    }                
    
    public void PromedioAnualBebidas(){
        double suma = 0.0;
        double promedio = 0.0;
        for(Double d: ListaBebidas)
            suma+=d;
        promedio = suma/ListaBebidas.size();
        this.txtpromedioanual.setText(""+promedio);        
    }
    
    public void menorCostoBebidas(){
        double min = ListaBebidas.get(0);
        int indice=0;
        for(int i=0;i<ListaBebidas.size();i++)
            if(ListaBebidas.get(i)<=min)
                indice = i;
        this.txtmesmenorregistro.setText(MES.get(indice));
    }
    
    public void menorProduccionAgosto(){
               
        if(ListaBebidas.get(7)<=ListaConservas.get(7)){
            if(ListaBebidas.get(7)<=ListaDulces.get(7)){
                this.txtdepartamentomenorproduccion.setText("Dep : BEBIDAS Menor Costo");
            }else if(ListaDulces.get(7)<=ListaConservas.get(7)){
                this.txtdepartamentomenorproduccion.setText("Dep : DULCES Menor Costo");
            }else 
                this.txtdepartamentomenorproduccion.setText("Dep : CONSERVAS Menor Costo");
        }else if(ListaConservas.get(7)<=ListaDulces.get(7)){
            this.txtdepartamentomenorproduccion.setText("Dep : CONSERVAS Menor Costo");
        }else
            this.txtdepartamentomenorproduccion.setText("Dep : DULCES Menor Costo");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcular;
    private javax.swing.JButton btngrabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtcantidadbebidas;
    private javax.swing.JTextField txtcantidadconcervas;
    private javax.swing.JTextField txtcantidaddulces;
    private javax.swing.JTextField txtdepartamentomenorproduccion;
    private javax.swing.JTextField txtmes;
    private javax.swing.JTextField txtmesmenorregistro;
    private javax.swing.JTextField txtmesproductomayor;
    private javax.swing.JTextField txtpromedioanual;
    // End of variables declaration//GEN-END:variables
}
