/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajoencargado4;

import java.util.ArrayList;

/**
 *
 * @author 20162
 */
public class ejercicio8 extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio8
     */
    ArrayList<Integer> ListaVecA;
    ArrayList<Integer> ListaVecB;
    ArrayList<Integer> ListaVecC;
    int tope;
    public ejercicio8() {
        initComponents();
        ListaVecA = new ArrayList<>();
        ListaVecB = new ArrayList<>();
        ListaVecC =  new ArrayList<>();
        tope=0;
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setTitle("ejercicio 08");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtvectorB = new javax.swing.JTextField();
        txtvectora = new javax.swing.JTextField();
        btngrabar = new javax.swing.JButton();
        btnmostrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtavectorC = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtareavectoaa = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtareavectorB = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Vector A");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 44, -1, -1));

        jLabel2.setText("Vector B");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));
        getContentPane().add(txtvectorB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 120, -1));
        getContentPane().add(txtvectora, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 120, -1));

        btngrabar.setText("GRABAR");
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btngrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        btnmostrar.setText("MOSTRAR");
        btnmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jLabel3.setText("Vector A");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel4.setText("Vector B");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        jLabel5.setText("Vector C");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        txtavectorC.setColumns(20);
        txtavectorC.setRows(5);
        jScrollPane1.setViewportView(txtavectorC);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 110, 180));

        txtareavectoaa.setColumns(20);
        txtareavectoaa.setRows(5);
        jScrollPane2.setViewportView(txtareavectoaa);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 110, 180));

        txtareavectorB.setColumns(20);
        txtareavectorB.setRows(5);
        jScrollPane3.setViewportView(txtareavectorB);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 110, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        // TODO add your handling code here:
        tope = Integer.parseInt(this.txtvectora.getText());
        llenado();
        mostrar();
        ListaVecC.clear();
    }//GEN-LAST:event_btngrabarActionPerformed

    private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarActionPerformed
        // TODO add your handling code here:
        multiC();
        this.txtavectorC.setText(cadC());
        txtavectorC.setEditable(false);
    }//GEN-LAST:event_btnmostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ejercicio8 ej =  new ejercicio8();
                ej.setVisible(true);
            }
        });
    }
    private int aleatorio(int min, int max){
        return (int)((max-min+1)*Math.random()+min);
    }
    
    private void restricVecA(int num){
        if(ListaVecA.size()<tope)
            ListaVecA.add(num);
        else
            throw new RuntimeException("Limite superado");
    }
    
    private void restricVecB(int num){
        if(ListaVecB.size()<tope)
            ListaVecB.add(num);
        else
            throw new RuntimeException("Limite superado");
    }
    
    public void llenado(){
        for(int i=0;i<tope-1;i++){
            restricVecA(aleatorio(0, 10));
            restricVecB(aleatorio(0, 10));
        }
    }
    private void multiC(){
        int j = 0;
        int multi = 0;
        for(int i=ListaVecB.size()-1;i>=0;i--){
            multi=0;
            multi = ListaVecA.get(j)*ListaVecB.get(i);
            ListaVecC.add(multi);
            j++;
        }
    }
    
    public String cadA(){
        String cad = "";
        for(Integer i: ListaVecA)
            cad+=i+"\n";
        return cad;
    }
    
    public String cadB(){
        String cad = "";
        for(Integer i: ListaVecB)   
            cad+=i+"\n";
        return cad;
    }
    
    public String cadC(){
        String cad = "";
        for(Integer i: ListaVecC)
            cad+=i+"\n";
        return cad;
    }
    
    public void mostrar(){
        this.txtareavectoaa.setText(cadA());
        //this.txtareavectoaa.setEditable(false);
        this.txtareavectorB.setText(cadB());
        //this.txtareavectorB.setEditable(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngrabar;
    private javax.swing.JButton btnmostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtareavectoaa;
    private javax.swing.JTextArea txtareavectorB;
    private javax.swing.JTextArea txtavectorC;
    private javax.swing.JTextField txtvectorB;
    private javax.swing.JTextField txtvectora;
    // End of variables declaration//GEN-END:variables
}
