/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajoencargado4;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author 20162
 */
public class ejercicio3_1 extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio3_1
     */
    ArrayList<Integer> listanumero;
    ArrayList<Integer> listanueva;
    int contador = 0;

    public ejercicio3_1() {
        initComponents();
        listanumero = new ArrayList<>();
        listanueva = new ArrayList<>();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        btngrabar = new javax.swing.JButton();
        btnmostrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareainicial = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtareafinal = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtfinal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ingresar Numero: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));
        getContentPane().add(txtnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 120, -1));

        btngrabar.setText("GRABAR");
        btngrabar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btngrabarMouseClicked(evt);
            }
        });
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btngrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        btnmostrar.setText("MOSTRAR");
        btnmostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmostrarMouseClicked(evt);
            }
        });
        btnmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jLabel2.setText("Vector Inicial");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel3.setText("Vector Final");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        txtareainicial.setColumns(20);
        txtareainicial.setRows(5);
        jScrollPane1.setViewportView(txtareainicial);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 140, 110));

        txtareafinal.setColumns(20);
        txtareafinal.setRows(5);
        jScrollPane2.setViewportView(txtareafinal);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 150, 110));

        jLabel4.setText("Impresion Final");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));
        getContentPane().add(txtfinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        // TODO add your handling code here:
        try {
            
            if(txtnumero.getText()!=null){
                if(!Character.isDigit(Integer.parseInt(txtnumero.getText()))){
                    llenadoVecI();
                    this.txtareainicial.setText(cad1());        
                }
            }            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Solo Numeros");
        }
        this.txtnumero.setText("");
    }//GEN-LAST:event_btngrabarActionPerformed
    
    private void btngrabarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngrabarMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btngrabarMouseClicked

    private void btnmostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmostrarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnmostrarMouseClicked

    private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarActionPerformed
        // TODO add your handling code here:
        for(Integer i: listanumero){
            listanueva.add(i);
        }
        this.txtareafinal.setText(cad2());
        this.txtfinal.setText(listanueva.size()+"");
    }//GEN-LAST:event_btnmostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio3_1().setVisible(true);
            }
        });
    }

     public int aleatorio(int min,int max){
        return (int)((max-min+1)*Math.random()+min);
    }
    
    public void agrega(int num){
        if(listanumero.size()<=Integer.parseInt(txtnumero.getText())){
            listanumero.add(num);
        }
    }
    
    public void llenadoVecI(){
        int tam = Integer.parseInt(txtnumero.getText());
        for(int i=0;i<tam;i++){
            agrega(aleatorio(0,100));
        }
    }
    
    public String cad1(){
        String cad="";
        for(Integer i: listanumero)
            cad+=i+"\n";
        return cad;
    }
    
    public String cad2(){
        String cad="";
        for(Integer i: listanueva)
            cad+=i+"\n";
        return cad;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngrabar;
    private javax.swing.JButton btnmostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtareafinal;
    private javax.swing.JTextArea txtareainicial;
    private javax.swing.JTextField txtfinal;
    private javax.swing.JTextField txtnumero;
    // End of variables declaration//GEN-END:variables
}
