/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajoencargado4;

import java.util.ArrayList;
import java.util.Collections;

/**
 *
 * @author 20162
 */
public class ejercicio11 extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio11
     */
    ArrayList<Integer> lista;
    ArrayList<Integer> listaOrdenada;
    int tope;
    public ejercicio11() {
        initComponents();
        lista =  new ArrayList<>();
        listaOrdenada = new ArrayList<>();
        tope=0;
        this.setLocationRelativeTo(null);
        this.setTitle("ejercicio 11");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnmostrar = new javax.swing.JButton();
        btnordenar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaordenar = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtareamostrar = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtvectordireccion = new javax.swing.JTextField();
        txtposicion = new javax.swing.JTextField();
        txtresultado = new javax.swing.JTextField();
        txtbuscar = new javax.swing.JTextField();
        txtingresarnum = new javax.swing.JTextField();
        btngrabar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ingrese Numero:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 29, -1, -1));

        jLabel2.setText("Ingresar Numero a buscar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel3.setText("Resultado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel4.setText("N° de posiciones:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        btnmostrar.setText("MOSTRAR");
        btnmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        btnordenar.setText("ORDENAR");
        btnordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnordenarActionPerformed(evt);
            }
        });
        getContentPane().add(btnordenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        txtareaordenar.setColumns(20);
        txtareaordenar.setRows(5);
        jScrollPane1.setViewportView(txtareaordenar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 150, 180));

        txtareamostrar.setColumns(20);
        txtareamostrar.setRows(5);
        jScrollPane2.setViewportView(txtareamostrar);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 150, 180));

        jLabel5.setText("El vector esta: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));
        getContentPane().add(txtvectordireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 230, -1));
        getContentPane().add(txtposicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 130, -1));
        getContentPane().add(txtresultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 200, -1));
        getContentPane().add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 60, -1));
        getContentPane().add(txtingresarnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 60, -1));

        btngrabar.setText("GRABAR");
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btngrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        btnbuscar.setText("BUSCAR");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarActionPerformed
        // TODO add your handling code here:
        mostrar1();
        txtvectordireccion.setText("el vector  esta desordenado");
        //ordenLista1();
    }//GEN-LAST:event_btnmostrarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        buscandoNumero();
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        // TODO add your handling code here:
        tope = Integer.parseInt(this.txtingresarnum.getText());
        llenar(); 
        txtingresarnum.setText("");
        txtingresarnum.requestFocus();
    }//GEN-LAST:event_btngrabarActionPerformed

    private void btnordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnordenarActionPerformed
        // TODO add your handling code here:
        ordenLista2();
        txtvectordireccion.setText("el vector esta ordenado");
        mostrar2();
    }//GEN-LAST:event_btnordenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio11().setVisible(true);
            }
        });
    }
    private int aleatorio(int min, int max){
        return (int)((max-min+1)*Math.random()+min);
    }
    public void tamaño(int num){
        if(lista.size()<tope)
            lista.add(num);        
    }
    
    public void llenar(){
        for(int i=0;i<tope;i++)
            tamaño(aleatorio(0, 100));
    }
    public void mostrar1(){
        String cad = "";
        for(Integer i: lista)
            cad+=i+"\n";
        this.txtareamostrar.setText(cad);
        txtareamostrar.setEditable(false);
    }
    public void mostrar2(){
        String cad = "";
        for(Integer i: listaOrdenada)
            cad+=i+"\n";
        this.txtareaordenar.setText(cad);
        txtareaordenar.setEditable(false);
    }
     public void buscandoNumero(){
        int num = Integer.parseInt(this.txtbuscar.getText());
        int apariciones = 0;
        String cad = "";
        for(Integer i: lista){
            if(num==i){
                cad = " Numero encontrado ";
                apariciones++;
            }                
        }
        this.txtresultado.setText(cad);
        this.txtposicion.setText(apariciones+"");
    }
//     public boolean VerOrden(){
//        boolean ban = false;
//        int min = lista.get(0);
//        for(int i=1;i<lista.size();i++){
//            if(lista.get(i)>=min){
//                min = lista.get(i);
//                ban = true;
//            }else
//                return false;
//        }
//        return ban;
//    }
//     public void ordenLista1(){
//        if(VerOrden()){
//            this.txtvectordireccion.setText(" La lista está Ordenada");
//            txtvectordireccion.setEditable(false);
//        }else {
//            this.txtvectordireccion.setText(" La lista está Desordenada");
//            txtvectordireccion.setEditable(false);
//            
//        }
//    }
     public void ordenLista2(){
        for(Integer i: lista)
            listaOrdenada.add(i);
        Collections.sort(listaOrdenada);
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btngrabar;
    private javax.swing.JButton btnmostrar;
    private javax.swing.JButton btnordenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtareamostrar;
    private javax.swing.JTextArea txtareaordenar;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtingresarnum;
    private javax.swing.JTextField txtposicion;
    private javax.swing.JTextField txtresultado;
    private javax.swing.JTextField txtvectordireccion;
    // End of variables declaration//GEN-END:variables
}
