/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajoencargado4;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author 20162
 */
public class ejercicio4_1 extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio4_1
     */
    ArrayList<Integer> examen1;
    ArrayList<Integer> examen2;
    ArrayList<Integer> examen3;
    ArrayList<Double> promedioEst;
    int numalumno;
    int contador;
    public ejercicio4_1() {
        initComponents();
        examen1 =  new ArrayList<>();
        examen2 = new ArrayList<>();
        examen3 =  new ArrayList<>();
        promedioEst = new ArrayList<>();
        numalumno=0;
        contador =0;
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtnumestudiante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtexamen2 = new javax.swing.JTextField();
        txtexamen3 = new javax.swing.JTextField();
        txtexamen1 = new javax.swing.JTextField();
        btngrabar = new javax.swing.JButton();
        btncalcular = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtnumerodesaprobadosexamen1 = new javax.swing.JTextField();
        txtnumerodesaprobados = new javax.swing.JTextField();
        txtnumeroaprobados = new javax.swing.JTextField();
        txtnumeroestudiante = new javax.swing.JTextField();
        txtmayorpromedio = new javax.swing.JTextField();
        txtpromedioexamen3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Numero de orden del estudiante ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 25, -1, -1));
        getContentPane().add(txtnumestudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 70, -1));

        jLabel2.setText("Examen 2: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel3.setText("Examen 3: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel5.setText("Examen 1: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));
        getContentPane().add(txtexamen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 110, -1));
        getContentPane().add(txtexamen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 110, -1));
        getContentPane().add(txtexamen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 110, -1));

        btngrabar.setText("GRABAR");
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btngrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        btncalcular.setText("CALCULAR");
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btncalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel4.setText("Promedio del aula Examen 3 ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel6.setText("Mayor Promedio");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel7.setText("N° de estudiante");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel8.setText("N° de aprobados");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jLabel9.setText("N° de desaprobados");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jLabel10.setText("N° de desaprobados Examen 1");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));
        getContentPane().add(txtnumerodesaprobadosexamen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 60, -1));
        getContentPane().add(txtnumerodesaprobados, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 60, -1));
        getContentPane().add(txtnumeroaprobados, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 60, -1));
        getContentPane().add(txtnumeroestudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 60, -1));
        getContentPane().add(txtmayorpromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 110, -1));
        getContentPane().add(txtpromedioexamen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        // TODO add your handling code here:
        //this.txtnumestudiante.setEditable(false);       
        PromedioExamenes();
        cont++;
        numalumno = Integer.parseInt(txtnumestudiante.getText());
            
        agregarExamen1();                
        agregarExamen2();
        agregarExamen3();
        limpiar();
        if(cont==numalumno){
            btngrabar.setEnabled(true);            
        }                    
        //this.txtareadatos.setText("");
       
    }//GEN-LAST:event_btngrabarActionPerformed

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
        // TODO add your handling code here:
       this.txtpromedioexamen3.setText(PromExamen3()+"");
       this.txtpromedioexamen3.setEditable(false);
       
        this.txtmayorpromedio.setText(MayorProm()+"");
        this.txtmayorpromedio.setEditable(false);
        
        this.txtnumeroestudiante.setText(numalumno+"");
        this.txtnumeroestudiante.setEditable(false);
        
        this.txtnumeroaprobados.setText(numAprobados()+"");
        this.txtnumeroaprobados.setEditable(false);
        
        this.txtnumerodesaprobados.setText(numDesap()+"");
        this.txtnumerodesaprobados.setEditable(false);
        
        this.txtnumerodesaprobadosexamen1.setText(desExamen1()+"");
        this.txtnumerodesaprobadosexamen1.setEditable(false);
        
        //String cad = verNotas();
//        if(contador==numalumno){
//            this.txtareadatos.setText(verNotas());        
//            this.txtareadatos.setEditable(false);
//        }
        //this.txtnumestudiante.setText("");
//        this.btngrabar.setEnabled(true);
//        this.txtnumestudiante.setEditable(true);
    }//GEN-LAST:event_btncalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio4_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio4_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio4_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio4_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio4_1().setVisible(true);
            }
        });
    }
    public void agregarExamen1(){        
        if(examen1.size()<=numalumno)                         
            examen1.add(Integer.parseInt(this.txtexamen1.getText()));               
    }    
    public void agregarExamen2(){
        if(examen2.size()<=numalumno)
            examen2.add(Integer.parseInt(this.txtexamen2.getText()));                        
    }    
    public void agregarExamen3(){
        if(examen3.size()<=numalumno)
            examen3.add(Integer.parseInt(this.txtexamen3.getText()));
    }
    
    public String verExamen1(){
        String cad = "";
        for(Integer i: examen1)
            cad+=i+"\n";
        return cad;
    }
    
    public String verExamen2(){
        String cad = "";
        for(Integer i: examen1)
            cad+=i+"\n";
        return cad;
    }
    public String verExamen3(){
        String cad = "";
        for(Integer i: examen2)
            cad+=i+"\n";
        return cad;
    }
    
    public String verNotas(){
        String cad = "";
        int a = 1;
        for(int i=0;i<numalumno;i++){
            cad+="Promedio Alumno: "+a+"\nNotas: "+examen1.get(contador)+" , "+
                examen2.get(contador)+" , "+examen3.get(contador)+"\n";        
            contador++;
            a++;
        }
        return cad;
        
    }
    
    public double PromExamen3(){
        double suma = 0.0;
        for(Integer i: examen3)
            suma+=i;
        return suma/numalumno;
    }
    
    private void PromedioExamenes(){
        double suma1 = 0.0;
        double suma2 = 0.0;
        double suma3 = 0.0;
        int tam = Integer.parseInt(txtnumestudiante.getText());
        for(Integer i: examen1)
            suma1+=i;        
        for(Integer i: examen2)
            suma2+=i;
        for(Integer i: examen3)
            suma3+=i;
        double prom = (suma1+suma2+suma3)/3;
        promedioEst.add(prom);
    }
    
    public double MayorProm(){        
        double max = promedioEst.get(0);
        for(int i=0;i<promedioEst.size();i++)
            if(promedioEst.get(i)>max)
                max = promedioEst.get(i);
        
        return max;
    }
    
    public int numAprobados(){
        int cont=0;
        for(int i=0;i<promedioEst.size();i++){
            if(promedioEst.get(i)>=10.5)
                cont++;
        }
        return cont;
    }
    
    public int numDesap(){
        int cont=0;
        for(int i=0;i<promedioEst.size();i++){
            if(promedioEst.get(i)<10.5)
                cont++;
        }
        return cont;
    }
    
    public int desExamen1(){
        double suma = 0.0;
        double prom = 0.0;
        int cont=0;
        for(Integer i: examen1)
            suma+=i;
        prom = suma/examen1.size();        
        for(int i=0;i<examen1.size();i++)
            if(examen1.get(i)<10.5)
                cont++;       
        return cont;        
    }
    
    private int cont=0;
    
    public void limpiar(){
        txtnumestudiante.setText("");
        txtexamen1.setText("");
        txtexamen2.setText("");
        txtexamen3.setText("");
        txtnumestudiante.requestFocus();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcular;
    private javax.swing.JButton btngrabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtexamen1;
    private javax.swing.JTextField txtexamen2;
    private javax.swing.JTextField txtexamen3;
    private javax.swing.JTextField txtmayorpromedio;
    private javax.swing.JTextField txtnumeroaprobados;
    private javax.swing.JTextField txtnumerodesaprobados;
    private javax.swing.JTextField txtnumerodesaprobadosexamen1;
    private javax.swing.JTextField txtnumeroestudiante;
    private javax.swing.JTextField txtnumestudiante;
    private javax.swing.JTextField txtpromedioexamen3;
    // End of variables declaration//GEN-END:variables
}
