/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajoencargado4;

import java.util.ArrayList;

/**
 *
 * @author 20162
 */
public class ejercicio02_1 extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio02_1
     */
    ArrayList<Integer> listanumero;
    int contador;
    int posicion;
    public ejercicio02_1() {
        initComponents();
        listanumero= new ArrayList<>();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        btngrabar = new javax.swing.JButton();
        btnmostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareatotal = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ingresar Numero: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 53, -1, -1));
        getContentPane().add(txtnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 160, -1));

        btngrabar.setText("GRABAR");
        btngrabar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btngrabarMouseClicked(evt);
            }
        });
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btngrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        btnmostrar.setText("MOSTRAR");
        btnmostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmostrarMouseClicked(evt);
            }
        });
        getContentPane().add(btnmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        txtareatotal.setColumns(20);
        txtareatotal.setRows(5);
        jScrollPane1.setViewportView(txtareatotal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 270, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btngrabarActionPerformed

    private void btngrabarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngrabarMouseClicked
        // TODO add your handling code here:
        int numero  = Integer.parseInt(txtnumero.getText());
        listanumero.add(numero);
        contador++;
        txtnumero.setText("");
        txtnumero.requestFocus();
    }//GEN-LAST:event_btngrabarMouseClicked

    private void btnmostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmostrarMouseClicked
        // TODO add your handling code here:
        int mayor=0;
        for (int i = 0; i <contador-1; i++) {
            int dif= listanumero.get(i)-listanumero.get(i+1);
            if (dif<0) {
                dif=dif*-1;
            }if (dif>mayor) {
                mayor=dif;
                posicion=i;
            }
        }
        txtareatotal.append("la mayor diferencia es: "+ " "+ mayor+"\n");
        txtareatotal.append("elementos: "+ " "+ posicion+" y "+ posicion+1+"\n");
    }//GEN-LAST:event_btnmostrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio02_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio02_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio02_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio02_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio02_1().setVisible(true);
            }
        });
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngrabar;
    private javax.swing.JButton btnmostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtareatotal;
    private javax.swing.JTextField txtnumero;
    // End of variables declaration//GEN-END:variables
}
